# Generated by Django 5.1.3 on 2025-05-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('url', models.URLField()),
                ('category', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('sentiment', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
