# Generated by Django 5.1.3 on 2025-05-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubuzz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summarize_article',
            field=models.TextField(blank=True),
        ),
    ]
