# Generated by Django 5.1.3 on 2025-05-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubuzz', '0002_article_summarize_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
