# Generated by Django 5.1.3 on 2025-05-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubuzz', '0003_alter_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='source_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='source_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='url_to_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='location',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
