# Generated by Django 5.1.3 on 2025-05-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubuzz', '0004_remove_article_category_remove_article_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
